import type { Metadata } from 'next';
import { BrandGallery } from '@/components/sections/brand-gallery';
import { APP_URL } from '@/lib/utils';
import { ArrowRight } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Brand Gallery',
  description:
    'Explore brands created by real creators on Brand Me Now. See logos, color palettes, product mockups, and full brand identities.',
  openGraph: {
    title: 'Brand Gallery | Brand Me Now',
    description:
      'Explore brands created by real creators using AI-powered brand generation.',
    url: 'https://brandmenow.com/brand-gallery',
    images: [{ url: '/og/default.png', width: 1200, height: 630 }],
  },
};

export default function BrandGalleryPage() {
  return (
    <div className="min-h-screen">
      {/* Header */}
      <section className="pb-4 pt-16 text-center">
        <div className="mx-auto max-w-3xl px-4">
          <p className="mb-2 text-sm font-semibold uppercase tracking-wider text-[var(--bmn-color-accent)]">
            Showcase
          </p>
          <h1
            className="text-4xl font-bold tracking-tight sm:text-5xl"
            style={{ fontFamily: 'var(--bmn-font-secondary)' }}
          >
            Brand Gallery
          </h1>
          <p className="mt-4 text-lg text-[var(--bmn-color-text-secondary)]">
            See what creators have built with Brand Me Now. Every brand below
            was generated by AI in under 15 minutes.
          </p>
        </div>
      </section>

      <BrandGallery />

      {/* CTA */}
      <section className="border-t border-[var(--bmn-color-border)] py-16 text-center">
        <div className="mx-auto max-w-2xl px-4">
          <h2
            className="text-2xl font-bold"
            style={{ fontFamily: 'var(--bmn-font-secondary)' }}
          >
            Your brand could be next
          </h2>
          <p className="mt-2 text-[var(--bmn-color-text-secondary)]">
            Start building your brand identity, logos, and product mockups
            today.
          </p>
          <a
            href={`${APP_URL}/signup`}
            className="group mt-6 inline-flex items-center gap-2 rounded-xl bg-[var(--bmn-color-primary)] px-6 py-3 text-sm font-semibold text-[var(--bmn-color-primary-foreground)] transition-all hover:bg-[var(--bmn-color-primary-hover)] hover:shadow-lg"
          >
            Start Free
            <ArrowRight
              size={16}
              className="transition-transform group-hover:translate-x-0.5"
            />
          </a>
        </div>
      </section>
    </div>
  );
}
