// server/src/skills/name-generator/tools.js

import { z } from 'zod';

// ---- Input Schemas -------------------------------------------------------

export const SuggestBrandNamesInput = z.object({
  suggestions: z.array(z.object({
    name: z.string().min(1).max(50).describe('The brand name suggestion'),
    strategy: z.enum([
      'descriptive',
      'evocative',
      'compound',
      'abstract',
      'metaphorical',
      'acronym',
      'personal',
    ]).describe('Naming strategy used'),
    reasoning: z.string().min(20).max(300).describe('Why this name fits the brand'),
    confidenceScore: z.number().min(0).max(1).describe('Confidence this name is a good fit (0-1)'),
    pronunciationGuide: z.string().nullable().describe('How to pronounce the name if non-obvious'),
    tagline: z.string().nullable().describe('Optional tagline suggestion to pair with the name'),
  })).min(5).max(10),
});

export const CheckDomainAvailabilityInput = z.object({
  names: z.array(z.string()).min(1).max(10).describe('Brand names to check domains for'),
  extensions: z.array(z.string()).default(['.com', '.co', '.io', '.shop', '.store']).describe('Domain extensions to check'),
});

export const CheckTrademarkConflictsInput = z.object({
  names: z.array(z.string()).min(1).max(10).describe('Brand names to check for trademark conflicts'),
  industryCategory: z.string().describe('Industry category for trademark search scope'),
});

export const SaveNameSuggestionsInput = z.object({
  brandId: z.string().uuid(),
  userId: z.string().uuid(),
  suggestions: z.array(z.object({
    name: z.string(),
    strategy: z.string(),
    reasoning: z.string(),
    confidenceScore: z.number(),
    pronunciationGuide: z.string().nullable(),
    tagline: z.string().nullable(),
    domainAvailability: z.record(z.string(), z.boolean()).nullable(),
    trademarkRisk: z.enum(['low', 'medium', 'high', 'unknown']).nullable(),
    trademarkNotes: z.string().nullable(),
  })),
});

// ---- Output Schemas ------------------------------------------------------

export const SuggestBrandNamesOutput = z.object({
  success: z.boolean(),
  suggestions: z.array(z.object({
    name: z.string(),
    strategy: z.string(),
    reasoning: z.string(),
    confidenceScore: z.number(),
    pronunciationGuide: z.string().nullable(),
    tagline: z.string().nullable(),
  })),
});

export const CheckDomainAvailabilityOutput = z.object({
  success: z.boolean(),
  results: z.record(z.string(), z.record(z.string(), z.boolean())).describe('{ "BrandName": { ".com": true, ".co": false } }'),
  error: z.string().nullable(),
});

export const CheckTrademarkConflictsOutput = z.object({
  success: z.boolean(),
  results: z.record(z.string(), z.object({
    risk: z.enum(['low', 'medium', 'high', 'unknown']),
    notes: z.string(),
    similarMarks: z.array(z.string()),
  })),
  error: z.string().nullable(),
});

export const SaveNameSuggestionsOutput = z.object({
  success: z.boolean(),
  brandId: z.string().uuid(),
  savedCount: z.number(),
  error: z.string().nullable(),
});

// ---- Tool Definitions ----------------------------------------------------

/** @type {Array<{ name: string, description: string, inputSchema: import('zod').ZodType, outputSchema: import('zod').ZodType }>} */
export const tools = [
  {
    name: 'suggestBrandNames',
    description: 'Structure and validate 5-10 brand name suggestions generated by the AI agent. Each suggestion includes the name, strategy, reasoning, confidence score, and optional pronunciation guide. Call this FIRST.',
    inputSchema: SuggestBrandNamesInput,
    outputSchema: SuggestBrandNamesOutput,
  },
  {
    name: 'checkDomainAvailability',
    description: 'Check domain availability for all suggested names across .com, .co, .io, .shop, and .store extensions using RDAP lookup with DNS fallback. Call this SECOND.',
    inputSchema: CheckDomainAvailabilityInput,
    outputSchema: CheckDomainAvailabilityOutput,
  },
  {
    name: 'checkTrademarkConflicts',
    description: 'Screen all suggested names for basic trademark conflicts in the relevant industry category. Uses USPTO TESS with heuristic fallback. Call this THIRD.',
    inputSchema: CheckTrademarkConflictsInput,
    outputSchema: CheckTrademarkConflictsOutput,
  },
  {
    name: 'saveNameSuggestions',
    description: 'Save all name suggestions with domain and trademark data to the brand record in Supabase. Call this LAST.',
    inputSchema: SaveNameSuggestionsInput,
    outputSchema: SaveNameSuggestionsOutput,
  },
];
