-- =============================================================================
-- 41_seed_subscriptions.sql — Subscription tier definitions (reference data)
-- =============================================================================

-- Subscription tiers are NOT stored as a database table.
-- They are defined as application config and referenced by:
--   1. The refill_credits() function (Section 4.4)
--   2. The Stripe product/price setup
--   3. The CHECK constraint on profiles.subscription_tier
--
-- This file documents the tier definitions for reference.

-- ┌──────────┬──────────┬────────┬──────────────┬────────────────┬─────────────────────────────┐
-- │ Tier     │ Price/mo │ Brands │ Logo Credits │ Mockup Credits │ Env Var for Stripe Price ID │
-- ├──────────┼──────────┼────────┼──────────────┼────────────────┼─────────────────────────────┤
-- │ free     │ $0       │ 1      │ 4            │ 4              │ (no Stripe price)           │
-- │ starter  │ $29      │ 3      │ 20           │ 30             │ STRIPE_PRICE_STARTER        │
-- │ pro      │ $79      │ 10     │ 50           │ 100            │ STRIPE_PRICE_PRO            │
-- │ agency   │ $199     │ Unlim  │ 200          │ 500            │ STRIPE_PRICE_AGENCY         │
-- └──────────┴──────────┴────────┴──────────────┴────────────────┴─────────────────────────────┘
--
-- NOTE: Stripe Price IDs are NOT stored in the database. They are configured via
-- environment variables (see .env.example) and read by server/src/config/tiers.js.
-- Defaults: price_starter_monthly, price_pro_monthly, price_agency_monthly.
-- Replace with real Stripe Price IDs after creating products in the Stripe Dashboard.
--
-- Credits refresh monthly. Unused credits do NOT roll over. Overage at per-unit rates.
--
-- After user signup, call:
--   SELECT public.refill_credits('<user-uuid>', 'free');
-- to provision the initial free-tier credits.
